language: php
sudo: false
dist: trusty
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_script:
  - pecl install xmldiff
  - composer self --1
  - echo "xdebug.max_nesting_level=1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [[ $TRAVIS_PHP_VERSION == '7.'* ]]; then composer --dev require ocramius/package-versions:^1.0 --no-update; fi

  - composer update $COMPOSER_FLAGS

script:
  - vendor/phpunit/phpunit/phpunit $PHPUNIT_FLAGS
  - bin/xsd2php convert tests/config.yml tests/JmsSerializer/OTA/otaxml/OTA_AirAvailRQ.xsd -vv

